// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzhbvcpaRYlhmzSdqihDRauEjiIYmZWbk',
    appId: '1:982718657096:web:15625e1f2d355d636b1e7d',
    messagingSenderId: '982718657096',
    projectId: 'grafos-2e8f4',
    authDomain: 'grafos-2e8f4.firebaseapp.com',
    storageBucket: 'grafos-2e8f4.appspot.com',
    measurementId: 'G-D65Z62YZ73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuVLxq59ZYsIrX7h-ptiurhWR4q8pcIlU',
    appId: '1:982718657096:android:788a0ecbfd72135a6b1e7d',
    messagingSenderId: '982718657096',
    projectId: 'grafos-2e8f4',
    storageBucket: 'grafos-2e8f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOsA7OBcF_HXGql-hzR-3XTHAmYNge3IY',
    appId: '1:982718657096:ios:a241d2079eff2de36b1e7d',
    messagingSenderId: '982718657096',
    projectId: 'grafos-2e8f4',
    storageBucket: 'grafos-2e8f4.appspot.com',
    iosClientId: '982718657096-r63q133i2ea8kobs16achleg4bqq0ipl.apps.googleusercontent.com',
    iosBundleId: 'com.example.grafos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOsA7OBcF_HXGql-hzR-3XTHAmYNge3IY',
    appId: '1:982718657096:ios:a241d2079eff2de36b1e7d',
    messagingSenderId: '982718657096',
    projectId: 'grafos-2e8f4',
    storageBucket: 'grafos-2e8f4.appspot.com',
    iosClientId: '982718657096-r63q133i2ea8kobs16achleg4bqq0ipl.apps.googleusercontent.com',
    iosBundleId: 'com.example.grafos',
  );
}
